sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: sdran

  redis:
    host: localhost
    port: 6379
    database: 10


  wechat:
    secret: 5d5f79a08e60b6dddce895d46d71bf08
    appid: wx3176091dd3a4c7c8